version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golocacao
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./banco/mysql:/var/lib/mysql
      - ./banco/init:/docker-entrypoint-initdb.d
    networks:
      - mynet

  backend:
    image: golang:1.17
    container_name: backend
    volumes:
      - ./:/go/src
    ports:
      - 3000:3000
    depends_on:
      - mysql
    command: bash -c "cd /go/src && GOOS=linux go build main.go && go run main.go"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.28.1.0/16"

