version: '3'

services:
    db:
        image: mysql:8.0
        ports:
          - 3306:3306
        volumes:
          - ./banco/mysql:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_PASSWORD=root
          - MYSQL_USER=root
          - MYSQL_DATABASE=golocacao

    backend:
        image: golang
        volumes: 
            - ./:/backend
        ports: 
            - 3000:3000
        restart: on-failure
        depends_on:
          - db
        links:
          - db
        environment:
          - DB_HOST=db
          - DB_PORT=3306
          - DB_NAME=golocacao
          - DB_USER=root
          - DB_PASS=root
        command: bash -c "cd /backend && go run main.go"
